# Generated by Django 5.2.6 on 2025-11-12 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_bus_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='ROUTE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.route'),
        ),
    ]
