# Generated by Django 5.2.6 on 2025-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_bus_route_bus_fromroute_bus_to_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
