# Generated by Django 5.2.6 on 2025-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_no',
            field=models.IntegerField(),
        ),
    ]
