# Generated by Django 5.2.6 on 2025-12-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
