# Generated by Django 5.2.6 on 2025-12-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_users_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='state',
        ),
    ]
