# Generated by Django 5.2.6 on 2025-12-26 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_loacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bus')),
            ],
        ),
    ]
