# Generated by Django 5.2.6 on 2025-11-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_driver_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='ROUTE',
        ),
    ]
