# Generated by Django 5.2.6 on 2025-11-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bus_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='ROUTE',
        ),
        migrations.AddField(
            model_name='bus',
            name='FromROUTE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='to_route', to='myapp.route'),
        ),
        migrations.AddField(
            model_name='bus',
            name='To_ROUTE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='from_route', to='myapp.route'),
        ),
    ]
