# Generated by Django 5.2.6 on 2025-12-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_fair'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('FROMSTOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop', to='myapp.stop')),
                ('TOSTOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stop', to='myapp.stop')),
            ],
        ),
        migrations.DeleteModel(
            name='Fair',
        ),
    ]
