# Generated by Django 5.2.6 on 2025-12-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ticketprize_delete_fair'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
